In [1]:
import module as md

In [45]:
data=md.pd.read_csv("loan_approval_dataset.csv")
# data=md.pd.read_csv("kc_house_data.csv")

In [40]:
data.sample()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
2100,3,Not Graduate,No,4500000,16400000,6,533,1800000,5600000,12200000,3900000,Rejected

In [50]:
# data.drop(["loan_id"], axis=1)
data = data.drop(columns=["no_of_dependents", ])
# data = data.drop(columns=["loan_id", "no_of_dependents", "residential_assets_value","commercial_assets_value","luxury_assets_value","bank_asset_value"])
# data = data.drop(columns=["loan_id", "no_of_dependents", "residential_assets_value","commercial_assets_value","luxury_assets_value","bank_asset_value"])

KeyError: "['no_of_dependents'] not found in axis"

In [51]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

## COVID-19

In [1]:
import module as md

In [6]:
data={
    "Fever": [98,99,100,101,102,103,98,99,101,102],
    "Cough": [0,0,1,1,1,1,0,1,1,1],
    "BreathingProblem":[0,0,0,1,1,1,0,0,1,1],
    "COVID_Status":[
        "Negative", "Negative", "Negative",
        "Positive","Positive","Positive",
        "Negative", "Negative", "Positive","Positive"
    ]
}

df= md.pd.DataFrame(data)

x=df[["Fever", "Cough", "BreathingProblem"]]
y=df["COVID_Status"]

model= md.DecisionTreeClassifier()

model.fit(x,y)

fever=float(input("Enter Temperature (°F)): "))
cough=float(input("Cough?  (1=Yes, 0=No): "))
breathing=float(input("Breathing  Problem (1=Yes, 0=No): "))

prediction=model.predict([[fever, cough, breathing]])
print("COVID Status: ", prediction[0])

y_pred=model.predict(x)
accuracy=md.accuracy_score(y,y_pred)
print("Accuracy:", accuracy*100, "%")

COVID Status:  Negative
Accuracy: 100.0 %

c:\Users\akmma\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(