In [5]:
import pandas as jd

In [6]:
f1=jd.read_csv("Pokemon.csv")
f1

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,3,Gigantamax Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,896,Glastrier,Ice,NaN,580,100,145,130,65,110,30,8,True
1068,897,Spectrier,Ghost,NaN,580,100,65,60,145,80,130,8,True
1069,898,Calyrex,Psychic,Grass,500,100,80,80,80,80,80,8,True
1070,898,Ice Rider Calyrex,Psychic,Ice,680,100,165,150,85,130,50,8,True
1071,898,Shadow Rider Calyrex,Psychic,Ghost,680,100,85,80,165,100,150,8,True

In [17]:
f1.head()
f1.tail()
f1.shape
f1.ndim
f1.size
f1.dtypes

number        int64
name            str
type1           str
type2           str
total         int64
hp            int64
attack        int64
defense       int64
sp_attack     int64
sp_defense    int64
speed         int64
generation    int64
legendary      bool
dtype: object

In [19]:
# read specific Column
f1=jd.read_csv(
    "Pokemon.csv",
    usecols=["name", "type1"]
    )
f1

                      name    type1
0                Bulbasaur    Grass
1                  Ivysaur    Grass
2                 Venusaur    Grass
3            Mega Venusaur    Grass
4      Gigantamax Venusaur    Grass
...                    ...      ...
1067             Glastrier      Ice
1068             Spectrier    Ghost
1069               Calyrex  Psychic
1070     Ice Rider Calyrex  Psychic
1071  Shadow Rider Calyrex  Psychic

[1072 rows x 2 columns]