In [5]:
import pandas as jd

In [6]:
f1=jd.read_csv("Pokemon.csv")
f1

,number,name,type1,type2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,3,Gigantamax Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1067,896,Glastrier,Ice,NaN,580,100,145,130,65,110,30,8,True
1068,897,Spectrier,Ghost,NaN,580,100,65,60,145,80,130,8,True
1069,898,Calyrex,Psychic,Grass,500,100,80,80,80,80,80,8,True
1070,898,Ice Rider Calyrex,Psychic,Ice,680,100,165,150,85,130,50,8,True
1071,898,Shadow Rider Calyrex,Psychic,Ghost,680,100,85,80,165,100,150,8,True

In [17]:
f1.head()
f1.tail()
f1.shape
f1.ndim
f1.size
f1.dtypes

number        int64
name            str
type1           str
type2           str
total         int64
hp            int64
attack        int64
defense       int64
sp_attack     int64
sp_defense    int64
speed         int64
generation    int64
legendary      bool
dtype: object

In [21]:
# read specific Column
f1=jd.read_csv(
    "Pokemon.csv",
    usecols=["name", "type1"]
    )
f1

                      name    type1
0                Bulbasaur    Grass
1                  Ivysaur    Grass
2                 Venusaur    Grass
3            Mega Venusaur    Grass
4      Gigantamax Venusaur    Grass
...                    ...      ...
1067             Glastrier      Ice
1068             Spectrier    Ghost
1069               Calyrex  Psychic
1070     Ice Rider Calyrex  Psychic
1071  Shadow Rider Calyrex  Psychic

[1072 rows x 2 columns]

In [29]:
# read specific Column
f1=jd.read_csv(
    "Pokemon.csv",
    names=["name", "type1"]
    )
f1

                                                                                                      name  \
number name                 type1   type2  total hp  attack defense sp_attack sp_defense speed  generation
1      Bulbasaur            Grass   Poison 318   45  49     49      65        65         45              1
2      Ivysaur              Grass   Poison 405   60  62     63      80        80         60              1
3      Venusaur             Grass   Poison 525   80  82     83      100       100        80              1
       Mega Venusaur        Grass   Poison 625   80  100    123     122       120        80              1
...                                                                                                    ...
896    Glastrier            Ice     nan    580   100 145    130     65        110        30              8
897    Spectrier            Ghost   nan    580   100 65     60      145       80         130             8
898    Calyrex              Psychic Grass  500   100 80     80      80        80         80              8
       Ice Rider Calyrex    Psychic Ice    680   100 165    150     85        130        50              8
       Shadow Rider Calyrex Psychic Ghost  680   100 85     80      165       100        150             8

                                                                                                    type1
number name                 type1   type2  total hp  attack defense sp_attack sp_defense speed  legendary
1      Bulbasaur            Grass   Poison 318   45  49     49      65        65         45         FALSE
2      Ivysaur              Grass   Poison 405   60  62     63      80        80         60         FALSE
3      Venusaur             Grass   Poison 525   80  82     83      100       100        80         FALSE
       Mega Venusaur        Grass   Poison 625   80  100    123     122       120        80         FALSE
...                                                                                                   ...
896    Glastrier            Ice     nan    580   100 145    130     65        110        30          TRUE
897    Spectrier            Ghost   nan    580   100 65     60      145       80         130         TRUE
898    Calyrex              Psychic Grass  500   100 80     80      80        80         80          TRUE
       Ice Rider Calyrex    Psychic Ice    680   100 165    150     85        130        50          TRUE
       Shadow Rider Calyrex Psychic Ghost  680   100 85     80      165       100        150         TRUE

[1073 rows x 2 columns]

In [24]:
file=pd.read_json("train.json")
file

,train_no,train_name,route,route_code,KMT,WL,BPQ,NGP,BCT,ST,KOTA,JP,NDLS
0,13240,Kota-Patna Express,"[Kota, Indargarh Sumerganj Mandi, Sawai Madhop...","{'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13238,Kota-Patna Express,"[Kota, Indargarh Sumerganj Mandi, Sawai Madhop...","{'KOTA': 'Kota', 'IDG': 'Indargarh Sumerganj M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13237,Patna-Kota Express,"[Patna, Danapur, Bihta, Ara, Dumroan, Buxar, Z...","{'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13239,Patna-Kota Express,"[Patna, Danapur, Bihta, Ara, Buxar, Zamania, P...","{'PNBE': 'Patna', 'DNR': 'Danapur', 'BTA': 'Bi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12239,Hisar Duronto Express,"[Ratlam, Kota, Sawai Madhopur, Jaipur]","{'RTM': 'Ratlam', 'KOTA': 'Kota', 'SWM': 'Sawa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12465,Ranthambhore SF Express,"[Dakaniya Talav, Kota, Kapren, Lakheri, Indarg...","{'DKAE': 'Dakaniya Talav', 'KOTA': 'Kota', 'KP...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,22933,Jaipur SF Express,"[Bandra Terminus, Borivali, Vapi, Surat, Bharu...","{'BDTS': 'Bandra Terminus', 'BVI': 'Borivali',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22935,Jaipur SF Express,"[Jaipur, Durgapura, Sawai Madhopur, Kota, Ramg...","{'SWM': 'Sawai Madhopur', 'KOTA': 'Kota', 'RMA...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,12955,Mumbai Central Jaipur SF Express,"[Mumbai Central, Borivali, Vapi, Surat, Ankles...","{'BCT': 'Mumbai Central', 'BVI': 'Borivali', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,67890,Kolkata-Delhi Superfast,"[Kolkata, Patna, Varanasi, Kanpur Central, Luc...","{'Kolkata': 'Kolkata', 'PNBE': 'Patna', 'BSB':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,12904,Golden Temple Mail,"[Hazrat Nizamuddin, Faridabad, Mathura, Bharat...","{'NZM': 'Hazrat Nizamuddin', 'FDB': 'Faridabad...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12622,Tamil Nadu Express,"[New Delhi, Agra Cantt, Gwalior, VGL Jhansi, B...","{'NDLS': 'New Delhi', 'AGC': 'Agra Cantt', 'GW...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10622,Delhi Chennai Rajdhani Express,"[New Delhi, Jaipur, Kota, Surat, Mumbai , Nagp...","{'NDLS': 'New Delhi', 'JP': 'Jaipur', 'KOTA': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,12424,Dibrugarh Rajdhani Express,"[New Delhi, Jaunpur Central, Prayagraj, Pt.DD ...","{'NDLS': 'New Delhi', 'JNU': 'Jaunpur Junction...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20506,Dibrugarh Rajdhani Express,"[New Delhi, Moradabad, Bareilly, Lucknow, Vara...","{'NDLS': 'New Delhi', 'MB': 'Moradabad', 'BE':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20503,New Delhi Rajdhani Express,"[Dibrugarh, North Lakhimpur, Harmuti, Rangapar...","{'DBRG': 'Dibrugarh', 'NLP': 'North Lakhimpur'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,10324,Dibrugarh Rajdhani Express,"[Dibrugarh, Dimapur, Rangia, Guwahati, Patna, ...","{'DBRG': 'Dibrugarh', 'DMV': 'Dimapur', 'RNY':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,10623,Delhi Rajdhani Express,"[Chennai, Vijayawada, Khammam, Warangal, Balha...","{'MAS': 'Chennai Central', 'BZA': 'Vijayawada'...",Khammam,Warangal,Balharshah,Nagpur,Mumbai Central,Surat,Kota,Jaipur,New Delhi
18,15667,Kamakhya Express,"[Kota, Sawai Madhopur, Bayana, Agra Fort, Tund...","{'KOTA': 'Kota', 'SWM': 'Sawai Madhopur', 'BXN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,15635,Guwahati Dwarka Express,"[Okha, Dwarka, Khambhalia, Jamnagar, Hapa, Raj...","{'OKHA': 'Okha', 'DWK': 'Dwarka', 'KMBL': 'Kha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,22436,Varanasi Vande Bharat Express,"[New Delhi, Kanpur Central, Prayagraj , Varana...","{'NDLS': 'New Delhi', 'CNB': 'Kanpur Central',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22437,Varanasi Vande Bharat Express,"[Varanasi, Prayagraj , Kanpur Central, New Delhi]","{'BSB': 'Varanasi', 'PRYJ': 'Prayagraj', 'CNB'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22438,Patna Vande Bharat Express,"[New Delhi, Patna]","{'NDLS': 'New Delhi', 'PNBE': 'Patna'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,22439,Patna Vande Bharat Express,"[Patna, New Delhi]","{'PNBE': 'Patna', 'NDLS': 'New Delhi'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pk=jd.DataFrame(file)
p1=jd.Series(pk["route_code"])
p1

In [ ]:
f1=jd.read_json(
    "train.json"
)

f1.train_name

In [ ]:
all=jd.DataFrame(f1)
all

In [2]:
import pandas as pan

In [31]:
f1=pan.read_csv("titanic.csv")
f1.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]>

In [32]:
f1.tail()
# f1.sample()
# f1.info()
# f1.describe()
# f1.memory_usage()
# f1.nunique()
pan.unique(f1["Name"])

<StringArray>
[                               'Kelly, Mr. James',
                'Wilkes, Mrs. James (Ellen Needs)',
                       'Myles, Mr. Thomas Francis',
                                'Wirz, Mr. Albert',
    'Hirvonen, Mrs. Alexander (Helga E Lindqvist)',
                      'Svensson, Mr. Johan Cervin',
                            'Connolly, Miss. Kate',
                    'Caldwell, Mr. Albert Francis',
       'Abrahim, Mrs. Joseph (Sophie Halaut Easu)',
                         'Davies, Mr. John Samuel',
 ...
                 'Riordan, Miss. Johanna Hannah""',
                       'Peacock, Miss. Treasteall',
                          'Naughton, Miss. Hannah',
 'Minahan, Mrs. William Edward (Lillian E Thorpe)',
                  'Henriksson, Miss. Jenny Lovisa',
                              'Spector, Mr. Woolf',
                    'Oliva y Ocana, Dona. Fermina',
                    'Saether, Mr. Simon Sivertsen',
                             'Ware, Mr. Frederick',
                        'Peter, Master. Michael J']
Length: 418, dtype: str